# Generated by Django 4.1.2 on 2022-11-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_track', '0002_personne_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='lastname',
        ),
    ]
